### ISSUE TITLE
Timeout using the bridge

### ISSUE THREAD

**Issue by sglebs** [fhoeben/hsac-xebium-bridge#1]
Hi @fhoeben ,

Originally I had this:

```
!define TEST_SYSTEM {slim} 
!path ./dependencies/*

!define slim.timeout {40}

|import|
|com.xebia.incubator.xebium|

|library |
|selenium driver fixture |

| script | selenium driver fixture |
| start browser | firefox | on url | http://localhost:7070/ |
| do | open | on | /files/ |
| ensure | do | sendKeys | on | id=upload-file | with | ${user.dir}/run.bat |
| ensure | do | clickAndWait | on | css=input[type="submit"] |
| stop browser |
```

I tried to use your bridge so that I could use your (excellent) storyboard:

```
!define TEST_SYSTEM {slim} 
!path ./dependencies/*

!define slim.timeout {40}

|Import                            |
|nl.hsac.fitnesse.fixture.slim     |
|nl.hsac.fitnesse.fixture.slim.web |
|nl.hsac.fitnesse.fixture.slim.web.xebium |

| script | selenium driver setup |
| start driver for | firefox |

|library |
|hsac selenium driver fixture |

| storyboard | hsac selenium driver fixture |
| start browser | firefox | on url | http://localhost:7070/ |
| do | open | on | /files/ |
| ensure | do | sendKeys | on | id=upload-file | with | ${user.dir}/run.bat |
| ensure | do | clickAndWait | on | css=input[type="submit"] |
| stop browser |
```

It opens the browser initially on http://localhost:7070/ but it never goes to /files/ , it gives a timeout:

```
do
Timed-out waiting (after 10s).
Page content:/Users/mqm/git/betdev-fitnesse/FitNesseRoot/files/screenshots/timeouts/HsacXebiumBrowserTest/timeout_6.png
open    on  /files/ Test not run
```

Did I miss anything? Thanks!

**Comment by sglebs** [comment]
Debugging the code I noticed that in SeleniumDriverFixture.setTimeoutOnSelenium, defaultWebDriverSupplier.getBrowser() is null. That is strange, no? I noticed because I have my own fork of Xebium, with this patch:

```
        if (defaultWebDriverSupplier.getBrowser().toLowerCase().equals("safari"))  //mqm fix for #137 - safari does not support this API
                return;
```

and because of your bridge I had to change it to:

```
        if (defaultWebDriverSupplier.getBrowser() != null &&  // mqm fix for use with the hsac bridge
                defaultWebDriverSupplier.getBrowser().toLowerCase().equals("safari"))  //mqm fix for #137 - safari does not support this API
                return;
```

   No idea if it is related to the timeout or not, but I figured I should mention it.

**Comment by sglebs** [comment]
I managed to make it work, like this:

```
!define TEST_SYSTEM {slim} 
!path ./dependencies/*

SEVERE: Killing slim client as exception occurred:java.net.SocketTimeoutException: Read timed out
https://github.com/unclebob/fitnesse/issues/653
https://github.com/unclebob/fitnesse/issues/657
!define slim.timeout {40}

|Import                            |
|nl.hsac.fitnesse.fixture.slim     |
|nl.hsac.fitnesse.fixture.slim.web |
|nl.hsac.fitnesse.fixture.slim.web.xebium |

| script | selenium driver setup |
| start driver for | firefox |

|library |
|hsac selenium driver fixture |

| storyboard | hsac selenium driver fixture |
| start browser | firefox | on url | http://localhost:7070/files/ |
| ensure | do | sendKeys | on | id=upload-file | with | ${user.dir}/run.bat |
| ensure | do | clickAndWait | on | css=input[type="submit"] |
| stop browser |
```

In other words, this does not seem to be supported (navigate to another relative URL):

```
| do | open | on | /files/ |
```

Am I correct?

**Comment by fhoeben** [comment]
I was just typing a message: try a full URL. You already found it

Indeed I have not looked at opening relative urls. I always used the fully qualified ones.
Open is supported, but with a full URL.

I have to look at the `defaultWebDriverSupplier.getBrowser()`

**Comment by fhoeben** [comment]
My code does not use the `defaultWebDriverSupplier` to create the selenium driver (it does it in the `selenium driver setup`), therefore its state is not filled.

**Comment by fhoeben** [comment]
I will create a fix to not mess with the `do open on` with a relative URL.

Can you confirm whether the relative url works if you use the fixture 
HsacBasicSeleniumDriverFixture (i.e. add 'basic' to the storyboard top row)?

Why do

```
|library |
|hsac selenium driver fixture |
```

That only seems required if you don't specify the fixture in your script or storyboard table...

**Comment by sglebs** [comment]
storyboard  hsac basic selenium driver fixture 
Could not invoke constructor for HsacBasicSeleniumDriverFixture[0]

**Comment by fhoeben** [comment]
Oops that will teach me: always create a default constructor....

**Comment by sglebs** [comment]
;-)

**Comment by fhoeben** [comment]
There is a default constructor now.

**Comment by fhoeben** [comment]
Relative URLs should be supported by 'do open on ...'

**Comment by sglebs** [comment]
Can you please update the mvn repository with this fix? I still get this problem when using this:

```
        <dependency>
                <groupId>nl.hsac</groupId>
                <artifactId>hsac-xebium-bridge</artifactId>
                <version>0.1.4</version>
        </dependency>
```

**Comment by fhoeben** [comment]
Try 0.1.5...
