### ISSUE TITLE
Error in method to take screenshot

### ISSUE THREAD

**Issue by psshyamvarma** [fhoeben/hsac-xebium-bridge#12]
First I'm not sure whether it is the right page to ask this question. But, I'm trying my luck as I did not get appropriate forum. Sorry about that.

In the first step, I have opened a new browser and opened and website. In second steps I'm calling a method to take screenshot. When running the wiki test, webbrowser is getting opened successfully but it has issue with the second method.

Error:
EXCEPTION:ABORT_SLIM_TEST:nl.hsac.fitnesse.fixture.slim.StopTestException: Cannot use Selenium before a driver is started (for instance using SeleniumDriverSetup)

Error screenshot:

https://user-images.githubusercontent.com/30441474/30179800-9d782e16-9405-11e7-9482-0421b68f690f.png

Below is the wiki code:

    !define TEST_SYSTEM {slim}

    !path C:\Shyam\Automation\Workspace\FitnesseTest\bin
    !path C:\Shyam\Automation\Fitnesse\Newjars\accessors-smart-1.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\asm-5.0.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\cglib-nodep-3.2.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-codec-1.6.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-collections-3.2.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-exec-1.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-io-2.5.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-lang3-3.4.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-logging-1.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-net-3.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\cssparser-0.9.20.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\diff-1.1.11.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\diffutils-1.2.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\fitnesse-20130530.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\fitnesse-standalone.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\freemarker-2.3.23.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\gson-2.3.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\guava-19.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\hamcrest-core-1.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\hsac-fitnesse-fixtures-2.9.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\hsac-fitnesse-plugin-1.18.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\hsac-xebium-bridge-0.5.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\htmllexer-2.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\htmlparser-2.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\htmlunit-2.23.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\htmlunit-core-js-2.23.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\htmlunit-driver-2.23.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\httpclient-4.3.6.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\httpcore-4.3.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\httpmime-4.3.6.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\jcl-over-slf4j-1.7.21.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\jna-4.1.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\jna-platform-4.1.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\json-20090211.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\json-path-2.2.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\json-smart-2.2.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\junit-4.12.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\neko-htmlunit-2.23.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\netty-3.5.7.Final.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\phantomjsdriver-1.3.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\sac-1.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-api-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-chrome-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-edge-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-firefox-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-ie-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-java-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-java-3.4.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-leg-rc-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-remote-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-safari-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-server-standalone-3.4.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-support-3.5.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\serializer-2.7.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\slf4j-api-1.7.21.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\slf4j-jdk14-1.7.21.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\testng-6.9.4.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\velocity-1.7.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\xalan-2.7.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\xebium-0.12.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\xercesImpl-2.11.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\xml-apis-1.4.01.jar

    !|Import|
    |demo|

    !|script:GoogleExp|
    |open|http://www.google.com|
    |takescreenshots|Foto_1|

Below is the java fixure code:

    package demo;

    import java.util.concurrent.TimeUnit;
    import nl.hsac.fitnesse.fixture.slim.web.xebium.HsacXebiumBrowserTest;
    import org.openqa.selenium.WebDriver;
    import org.openqa.selenium.chrome.ChromeDriver;

    public class GoogleExp {

    	    static WebDriver driver;

	    public GoogleExp(){

	    }

    public void open(String url){
      System.setProperty("webdriver.chrome.driver", "C://Shyam//Automation//ANT//chromedriver.exe");
      driver = new ChromeDriver();
      driver.get(url);
      driver.manage().window().maximize();
      driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
    }

    public HsacXebiumBrowserTest takescreenshots(String s){
 
	    HsacXebiumBrowserTest hxb = new HsacXebiumBrowserTest();
	    hxb.takeScreenshot(s);
	    return hxb;
    }

    }

**Comment by fhoeben** [comment]
You have come to the right place.

What the error is trying to tell you is that it `HsacXebiumBrowserTest` is not aware of the WebDriver instance you want to use (probably the one you created in your `open()` method) and is therefore unable to do anything for you.

Is there a particular reason you are writing your own Java code to setup Selenium (instead of using the supplied class `SeleniumDriverSetup` from the wiki)? 
And if you need your own code: is there a particular need for 'Xebium' support? `HsacXebiumBrowserTest` is intended to be used when running tests defined for 'Xebium' (i.e. the wiki page content uses the Xebium Selenium commands) but you also want to have tests, or just Selenium configuration, using hsac-fitnesse-fixtures.
Taking screenshots is a function already supported by Xebium (and slightly improved in de hsac-xebium bridge) so I would not imagine you would need to write any Java code for that.

If you are just defining a new test I would suggest you use hsac-fitnesse-fixtures (on its own and not the xebium bridge). The test in your question would look something like (but more/better examples can be found in the 'HsacExamples.SlimTests.BrowserTests' wiki page in that project):
```
!define TEST_SYSTEM {slim}
Workaround for https://github.com/unclebob/fitnesse/issues/989
!define slim.port {0}

The location when working standalone:
!path fixtures
!path fixtures/*.jar

When developing and changing the fixtures, we will work based on the pom.xml:
!pomFile ../pom.xml@compile

!note Everything up to here should be in 'top-level' wiki page (i.e. root of your test set)

!note Next part should be in SuiteSetUp wiki page

|Import                                     |
|nl.hsac.fitnesse.fixture.slim.web|

|script          |selenium driver setup|
|start driver for|chrome|

!note Now comes the part to put in your test page

|script|browser test|
|open|http://www.google.com|
|show|take screenshot|google|

!note Last part should be in SuiteTearDown page

|script|selenium driver setup|
|stop driver                 |


```
